/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	v12 "k8s.io/node-problem-detector/pkg/watchdog/client/listers/ecx/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	ecxv1 "k8s.io/node-problem-detector/pkg/watchdog/api/ecx/v1"
	versioned "k8s.io/node-problem-detector/pkg/watchdog/client/clientset/versioned"
	internalinterfaces "k8s.io/node-problem-detector/pkg/watchdog/client/informers/externalversions/internalinterfaces"
	v1 "k8s.io/node-problem-detector/pkg/watchdog/client/listers/ecx/v1"
)

// SelfHealingTaskInstanceInformer provides access to a shared informer and lister for
// SelfHealingTaskInstances.
type SelfHealingTaskInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v12.SelfHealingTaskInstanceLister
}

type selfHealingTaskInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSelfHealingTaskInstanceInformer constructs a new informer for SelfHealingTaskInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSelfHealingTaskInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSelfHealingTaskInstanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSelfHealingTaskInstanceInformer constructs a new informer for SelfHealingTaskInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSelfHealingTaskInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EcxV1().SelfHealingTaskInstances(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EcxV1().SelfHealingTaskInstances(namespace).Watch(options)
			},
		},
		&ecxv1.SelfHealingTaskInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *selfHealingTaskInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSelfHealingTaskInstanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *selfHealingTaskInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ecxv1.SelfHealingTaskInstance{}, f.defaultInformer)
}

func (f *selfHealingTaskInstanceInformer) Lister() v1.SelfHealingTaskInstanceLister {
	return v1.NewSelfHealingTaskInstanceLister(f.Informer().GetIndexer())
}
