//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTask) DeepCopyInto(out *SelfHealingTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTask.
func (in *SelfHealingTask) DeepCopy() *SelfHealingTask {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfHealingTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskList) DeepCopyInto(out *SelfHealingTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelfHealingTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskList.
func (in *SelfHealingTaskList) DeepCopy() *SelfHealingTaskList {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfHealingTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskSpec) DeepCopyInto(out *SelfHealingTaskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskSpec.
func (in *SelfHealingTaskSpec) DeepCopy() *SelfHealingTaskSpec {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskStatus) DeepCopyInto(out *SelfHealingTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskStatus.
func (in *SelfHealingTaskStatus) DeepCopy() *SelfHealingTaskStatus {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskStatus)
	in.DeepCopyInto(out)
	return out
}

//instance 实例

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskInstance) DeepCopyInto(out *SelfHealingTaskInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskInstance.
func (in *SelfHealingTaskInstance) DeepCopy() *SelfHealingTaskInstance {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfHealingTaskInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskInstanceList) DeepCopyInto(out *SelfHealingTaskInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelfHealingTaskInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskInstanceList.
func (in *SelfHealingTaskInstanceList) DeepCopy() *SelfHealingTaskInstanceList {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfHealingTaskInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskInstanceSpec) DeepCopyInto(out *SelfHealingTaskInstanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskInstanceSpec.
func (in *SelfHealingTaskInstanceSpec) DeepCopy() *SelfHealingTaskInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealingTaskInstanceStatus) DeepCopyInto(out *SelfHealingTaskInstanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealingTaskInstanceStatus.
func (in *SelfHealingTaskInstanceStatus) DeepCopy() *SelfHealingTaskInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(SelfHealingTaskInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
