/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	ecxv1 "k8s.io/node-problem-detector/pkg/watchdog/api/ecx/v1"
)

// FakeSelfHealingTasks implements SelfHealingTaskInterface
type FakeSelfHealingTasks struct {
	Fake *FakeEcxV1
	ns   string
}

var selfhealingtasksResource = schema.GroupVersionResource{Group: "ecx", Version: "v1", Resource: "selfhealingtasks"}

var selfhealingtasksKind = schema.GroupVersionKind{Group: "ecx", Version: "v1", Kind: "SelfHealingTask"}

// Get takes name of the selfHealingTask, and returns the corresponding selfHealingTask object, and an error if there is any.
func (c *FakeSelfHealingTasks) Get(name string, options v1.GetOptions) (result *ecxv1.SelfHealingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(selfhealingtasksResource, c.ns, name), &ecxv1.SelfHealingTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTask), err
}

// List takes label and field selectors, and returns the list of SelfHealingTasks that match those selectors.
func (c *FakeSelfHealingTasks) List(opts v1.ListOptions) (result *ecxv1.SelfHealingTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(selfhealingtasksResource, selfhealingtasksKind, c.ns, opts), &ecxv1.SelfHealingTaskList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ecxv1.SelfHealingTaskList{ListMeta: obj.(*ecxv1.SelfHealingTaskList).ListMeta}
	for _, item := range obj.(*ecxv1.SelfHealingTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested selfHealingTasks.
func (c *FakeSelfHealingTasks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(selfhealingtasksResource, c.ns, opts))

}

// Create takes the representation of a selfHealingTask and creates it.  Returns the server's representation of the selfHealingTask, and an error, if there is any.
func (c *FakeSelfHealingTasks) Create(selfHealingTask *ecxv1.SelfHealingTask) (result *ecxv1.SelfHealingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(selfhealingtasksResource, c.ns, selfHealingTask), &ecxv1.SelfHealingTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTask), err
}

// Update takes the representation of a selfHealingTask and updates it. Returns the server's representation of the selfHealingTask, and an error, if there is any.
func (c *FakeSelfHealingTasks) Update(selfHealingTask *ecxv1.SelfHealingTask) (result *ecxv1.SelfHealingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(selfhealingtasksResource, c.ns, selfHealingTask), &ecxv1.SelfHealingTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTask), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSelfHealingTasks) UpdateStatus(selfHealingTask *ecxv1.SelfHealingTask) (*ecxv1.SelfHealingTask, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(selfhealingtasksResource, "status", c.ns, selfHealingTask), &ecxv1.SelfHealingTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTask), err
}

// Delete takes name of the selfHealingTask and deletes it. Returns an error if one occurs.
func (c *FakeSelfHealingTasks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(selfhealingtasksResource, c.ns, name), &ecxv1.SelfHealingTask{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSelfHealingTasks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(selfhealingtasksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ecxv1.SelfHealingTaskList{})
	return err
}

// Patch applies the patch and returns the patched selfHealingTask.
func (c *FakeSelfHealingTasks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ecxv1.SelfHealingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(selfhealingtasksResource, c.ns, name, pt, data, subresources...), &ecxv1.SelfHealingTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTask), err
}
