/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	ecxv1 "k8s.io/node-problem-detector/pkg/watchdog/api/ecx/v1"
)

// FakeSelfHealingTaskInstances implements SelfHealingTaskInstanceInterface
type FakeSelfHealingTaskInstances struct {
	Fake *FakeEcxV1
	ns   string
}

var selfhealingtaskinstancesResource = schema.GroupVersionResource{Group: "ecx", Version: "v1", Resource: "selfhealingtaskinstances"}

var selfhealingtaskinstancesKind = schema.GroupVersionKind{Group: "ecx", Version: "v1", Kind: "SelfHealingTaskInstance"}

// Get takes name of the selfHealingTaskInstance, and returns the corresponding selfHealingTaskInstance object, and an error if there is any.
func (c *FakeSelfHealingTaskInstances) Get(name string, options v1.GetOptions) (result *ecxv1.SelfHealingTaskInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(selfhealingtaskinstancesResource, c.ns, name), &ecxv1.SelfHealingTaskInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTaskInstance), err
}

// List takes label and field selectors, and returns the list of SelfHealingTaskInstances that match those selectors.
func (c *FakeSelfHealingTaskInstances) List(opts v1.ListOptions) (result *ecxv1.SelfHealingTaskInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(selfhealingtaskinstancesResource, selfhealingtaskinstancesKind, c.ns, opts), &ecxv1.SelfHealingTaskInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ecxv1.SelfHealingTaskInstanceList{ListMeta: obj.(*ecxv1.SelfHealingTaskInstanceList).ListMeta}
	for _, item := range obj.(*ecxv1.SelfHealingTaskInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested selfHealingTaskInstances.
func (c *FakeSelfHealingTaskInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(selfhealingtaskinstancesResource, c.ns, opts))

}

// Create takes the representation of a selfHealingTaskInstance and creates it.  Returns the server's representation of the selfHealingTaskInstance, and an error, if there is any.
func (c *FakeSelfHealingTaskInstances) Create(selfHealingTaskInstance *ecxv1.SelfHealingTaskInstance) (result *ecxv1.SelfHealingTaskInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(selfhealingtaskinstancesResource, c.ns, selfHealingTaskInstance), &ecxv1.SelfHealingTaskInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTaskInstance), err
}

// Update takes the representation of a selfHealingTaskInstance and updates it. Returns the server's representation of the selfHealingTaskInstance, and an error, if there is any.
func (c *FakeSelfHealingTaskInstances) Update(selfHealingTaskInstance *ecxv1.SelfHealingTaskInstance) (result *ecxv1.SelfHealingTaskInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(selfhealingtaskinstancesResource, c.ns, selfHealingTaskInstance), &ecxv1.SelfHealingTaskInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTaskInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSelfHealingTaskInstances) UpdateStatus(selfHealingTaskInstance *ecxv1.SelfHealingTaskInstance) (*ecxv1.SelfHealingTaskInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(selfhealingtaskinstancesResource, "status", c.ns, selfHealingTaskInstance), &ecxv1.SelfHealingTaskInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTaskInstance), err
}

// Delete takes name of the selfHealingTaskInstance and deletes it. Returns an error if one occurs.
func (c *FakeSelfHealingTaskInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(selfhealingtaskinstancesResource, c.ns, name), &ecxv1.SelfHealingTaskInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSelfHealingTaskInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(selfhealingtaskinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ecxv1.SelfHealingTaskInstanceList{})
	return err
}

// Patch applies the patch and returns the patched selfHealingTaskInstance.
func (c *FakeSelfHealingTaskInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ecxv1.SelfHealingTaskInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(selfhealingtaskinstancesResource, c.ns, name, pt, data, subresources...), &ecxv1.SelfHealingTaskInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ecxv1.SelfHealingTaskInstance), err
}
