/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "k8s.io/node-problem-detector/pkg/watchdog/api/ecx/v1"
	scheme "k8s.io/node-problem-detector/pkg/watchdog/client/clientset/versioned/scheme"
)

// SelfHealingTaskInstancesGetter has a method to return a SelfHealingTaskInstanceInterface.
// A group's client should implement this interface.
type SelfHealingTaskInstancesGetter interface {
	SelfHealingTaskInstances(namespace string) SelfHealingTaskInstanceInterface
}

// SelfHealingTaskInstanceInterface has methods to work with SelfHealingTaskInstance resources.
type SelfHealingTaskInstanceInterface interface {
	Create(*v1.SelfHealingTaskInstance) (*v1.SelfHealingTaskInstance, error)
	Update(*v1.SelfHealingTaskInstance) (*v1.SelfHealingTaskInstance, error)
	UpdateStatus(*v1.SelfHealingTaskInstance) (*v1.SelfHealingTaskInstance, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SelfHealingTaskInstance, error)
	List(opts metav1.ListOptions) (*v1.SelfHealingTaskInstanceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SelfHealingTaskInstance, err error)
	SelfHealingTaskInstanceExpansion
}

// selfHealingTaskInstances implements SelfHealingTaskInstanceInterface
type selfHealingTaskInstances struct {
	client rest.Interface
	ns     string
}

// newSelfHealingTaskInstances returns a SelfHealingTaskInstances
func newSelfHealingTaskInstances(c *EcxV1Client, namespace string) *selfHealingTaskInstances {
	return &selfHealingTaskInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the selfHealingTaskInstance, and returns the corresponding selfHealingTaskInstance object, and an error if there is any.
func (c *selfHealingTaskInstances) Get(name string, options metav1.GetOptions) (result *v1.SelfHealingTaskInstance, err error) {
	result = &v1.SelfHealingTaskInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SelfHealingTaskInstances that match those selectors.
func (c *selfHealingTaskInstances) List(opts metav1.ListOptions) (result *v1.SelfHealingTaskInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SelfHealingTaskInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested selfHealingTaskInstances.
func (c *selfHealingTaskInstances) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a selfHealingTaskInstance and creates it.  Returns the server's representation of the selfHealingTaskInstance, and an error, if there is any.
func (c *selfHealingTaskInstances) Create(selfHealingTaskInstance *v1.SelfHealingTaskInstance) (result *v1.SelfHealingTaskInstance, err error) {
	result = &v1.SelfHealingTaskInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		Body(selfHealingTaskInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a selfHealingTaskInstance and updates it. Returns the server's representation of the selfHealingTaskInstance, and an error, if there is any.
func (c *selfHealingTaskInstances) Update(selfHealingTaskInstance *v1.SelfHealingTaskInstance) (result *v1.SelfHealingTaskInstance, err error) {
	result = &v1.SelfHealingTaskInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		Name(selfHealingTaskInstance.Name).
		Body(selfHealingTaskInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *selfHealingTaskInstances) UpdateStatus(selfHealingTaskInstance *v1.SelfHealingTaskInstance) (result *v1.SelfHealingTaskInstance, err error) {
	result = &v1.SelfHealingTaskInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		Name(selfHealingTaskInstance.Name).
		SubResource("status").
		Body(selfHealingTaskInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the selfHealingTaskInstance and deletes it. Returns an error if one occurs.
func (c *selfHealingTaskInstances) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *selfHealingTaskInstances) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched selfHealingTaskInstance.
func (c *selfHealingTaskInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SelfHealingTaskInstance, err error) {
	result = &v1.SelfHealingTaskInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("selfhealingtaskinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
