name: tag-release

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - version.txt

permissions:
  contents: read

jobs:
  tag:
    if: ${{ github.repository == 'kubernetes/node-problem-detector' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
        id: tag_release
    outputs:
      release_tag: ${{ steps.tag_release.outputs.release_tag }}
